# Generated by Django 5.0.6 on 2024-05-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfume',
            name='name',
        ),
    ]
