# Generated by Django 5.0.6 on 2024-05-29 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfume', '0003_customer_alter_perfume_image_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='is_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfume',
            name='sale_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 29, 14, 56, 51, 416991)),
        ),
    ]
